# Generated by Django 3.2.18 on 2023-04-20 08:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="national_card_image",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="national_card_number",
        ),
    ]
