# Generated by Django 3.2.18 on 2023-05-03 16:56

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_auto_20230420_1311"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="image",
            new_name="avatar",
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
    ]
