# Generated by Django 3.2.18 on 2023-05-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20230518_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='profile/default_avatar.jpg', upload_to='profile/'),
        ),
    ]
