# Generated by Django 3.2.18 on 2023-05-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_profile_bank_account_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
