# Generated by Django 3.2.18 on 2023-05-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charity", "0004_alter_donation_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="collected_amount",
            field=models.FloatField(default=0),
        ),
    ]
