# Generated by Django 3.2.18 on 2023-05-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charity", "0007_alter_donation_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="image",
            field=models.ImageField(default="ads/default.jpg", upload_to="ads/"),
        ),
    ]
