# Generated by Django 3.2.18 on 2023-05-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0008_alter_advertisement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='content',
            field=models.TextField(max_length=2000),
        ),
    ]
