# Generated by Django 3.2.18 on 2023-05-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charity", "0009_alter_advertisement_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="content",
            field=models.TextField(max_length=700),
        ),
    ]
